### ISSUE TITLE
[Enhancement] Explore usage of cache for bundles

### ISSUE THREAD

**Issue by adrianriobo** [praveenkumar/crc-github-action#4]
This will avoid download the bundle on every execution

**Comment by praveenkumar** [comment]
Do we have something which can be used for cache?

**Comment by adrianriobo** [comment]
As this is done in yaml syntax may we can use https://github.com/devtools-qe-incubator/pwt/blob/main/.github/workflows/build.yaml#L20 the thing about it we need the cahce key which should be the okd / ocp version I can try to create a PR and see how it works

**Comment by adrianriobo** [comment]
Fixed by #6
